### ISSUE TITLE
Rework the "Start videos paused" option

### ISSUE THREAD

**Issue by klemens** [klemens/ff-youtube-all-html5#33]
There are several issues in the current implementation:

* [x] #22 Distinguish foreground from background videos
* [x] ► is beeing displayed for paused videos in title (90241ccf1e38191002562c64ba19953b56e1728b)
* [x] Wrong quality is preloaded
* [x] #46 Are playlists working? Option to disable pausing for playlists?
* [x] ~~Intercept video.play() method~~ *Use DOM-events instead of the youtube api to be notified when the video starts* (8b5c7901f7ecbd1dfdf6e9fa6baa5064b29a770f)
* [ ] Pausing vs. stopping?

**Comment by klemens** [comment]
It seems we can hook into the native play method from html video elements and prevent playback there which should prevent the problems that sometimes (especially when several are opened at the same time) videos are played back for some time before they are paused.

**Comment by klemens** [comment]
The problem that videos play for a split second before being paused should be fixed with 8b5c7901f7ecbd1dfdf6e9fa6baa5064b29a770f, which is available in the latest beta.

So overwriting the play method no longer seems necessary: It is not very clean and also prevents the video from buffering while it is paused.
